
stages:
  - tests
  - image

.run_tests_template: &run_tests
  stage: tests
  tags:
    - docker
  script:
    - npm ci
    - npm run build
    - cd packages/runtime/ && npm run build  && cd -
    - npm link packages/runtime --unsafe-perm
    - npm run test

node-10-llvm-6:
  image: registry.gitlab.com/ovr/staticscript:node-10-llvm-6
  <<: *run_tests

node-10-llvm-7:
  image: registry.gitlab.com/ovr/staticscript:node-10-llvm-7
  <<: *run_tests

node-10-llvm-8:
  image: registry.gitlab.com/ovr/staticscript:node-10-llvm-8
  <<: *run_tests

node-11-llvm-6:
  image: registry.gitlab.com/ovr/staticscript:node-11-llvm-6
  <<: *run_tests

node-11-llvm-7:
  allow_failure: true
  image: registry.gitlab.com/ovr/staticscript:node-11-llvm-7
  <<: *run_tests

node-11-llvm-8:
  allow_failure: true
  image: registry.gitlab.com/ovr/staticscript:node-11-llvm-8
  <<: *run_tests

next:
  stage: image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/next/Dockerfile --destination $CI_REGISTRY_IMAGE:next
  only:
    - master
  tags:
    - docker

latest:
  stage: image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/latest/Dockerfile --destination $CI_REGISTRY_IMAGE:latest
  only:
    - master
  tags:
    - docker
